[package]
name = "cis0-client"
version = "0.1.0"
edition = "2018"

[dependencies]
concordium-rust-sdk = { path = "../deps/concordium-rust-sdk", version = "*" }
anyhow = "1"
tokio = {version = "1.8", features = ["full"]}
thiserror = "1.0"
clap = {version = "3.2", features = ["derive"]}

